language: php
php:
  - 5.5
  - 5.4
before_script:
  - composer install
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: phpunit  --coverage-clover=coverage.clover Tests/
after_script:
     - wget https://scrutinizer-ci.com/ocular.phar
     - php ocular.phar code-coverage:upload --format=php-clover coverage.clover